# Do not edit this file directly. It has been autogenerated from
# example_menu_async.py
import asyncio
import logging
import sys

from pystuderxcom import AsyncXcomFactory
from pystuderxcom import XcomFactory
from pystuderxcom import XcomVoltage, XcomFormat
from helper import RunHelper

# Setup logging to StdOut
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
logger = logging.getLogger(__name__)


def main():
    # Print entire menu structure
    dataset = XcomFactory.create_dataset(XcomVoltage.AC240) # or use XcomVoltage.AC120

    # Helper function to recursively print the entire menu
    def printMenu(parent, indent=""):
        items = dataset.getMenuItems(parent)
        for item in items:
            logger.info(f"{indent}{item.nr}: {item.name}")

            if item.format == XcomFormat.MENU:
                printMenu(item.nr, indent+"  ")

    printMenu(0)
    dataset = None  # Release memory of the dataset


RunHelper.run(main)  # main loop