# Do not edit this file directly. It has been autogenerated from
# example_discover_devices_async.py
import asyncio
from dataclasses import asdict
import logging
import sys

from pystuderxcom import AsyncXcomApiTcp, XcomApiTcp, XcomApiTcpMode
from pystuderxcom import AsyncXcomDiscover, XcomDiscover
from pystuderxcom import AsyncXcomFactory, XcomFactory
from pystuderxcom import XcomDataset, XcomVoltage
from helper import RunHelper

# Setup logging to StdOut
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
logger = logging.getLogger(__name__)


def main():
    api = XcomApiTcp(mode=XcomApiTcpMode.SERVER, listen_port=4001)    # port number configured in Xcom-LAN/Moxa NPort
    dataset = XcomFactory.create_dataset(XcomVoltage.AC240) # or use XcomVoltage.AC120

    try:
        if not api.start():
            logger.info(f"Did not connect to Xcom")
            return
        
        helper = XcomDiscover(api, dataset)

        # Discover Xcom client info
        client_info = helper.discover_client_info()

        logger.info(f"\n\n")
        logger.info(f"Discovered {client_info}")

        # Discover Xcom devices
        devices = helper.discover_devices(getExtendedInfo=True, verbose=False)

        logger.info(f"\n\n")
        for device in devices:
            logger.info(f"Discovered {device}")

        # Log diagnostic information
        diag = api.get_diagnostics()
        logger.info(f"Diagnostics: {diag}")

    finally:
        api.stop()
        dataset = None


RunHelper.run(main)  # main loop
