# Do not edit this file directly. It has been autogenerated from
# example_discover_devices_async.py
import asyncio
from dataclasses import asdict
import logging
import sys

from pystuderxcom import AsyncXcomApiTcp, XcomApiTcp, XcomApiTcpMode
from pystuderxcom import AsyncXcomDiscover, XcomDiscover
from pystuderxcom import XcomDataset, XcomVoltage
from helper import RunHelper

# Setup logging to StdOut
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
logger = logging.getLogger(__name__)


def main():
    dataset = XcomDataset.get_instance(XcomVoltage.AC240, XcomVoltage.DC48) # or use XcomVoltage.AC120, XcomVoltage.DC12 or XcomVoltagC.DC24 
    api = XcomApiTcp(mode=XcomApiTcpMode.SERVER, listen_port=4001)    # port number configured in Xcom-LAN/Moxa NPort

    try:
        if not api.start():
            logger.info(f"Did not connect to Xcom")
            return
        
        helper = XcomDiscover(api, dataset)

        # Discover Xcom gateway info
        gw_info = helper.discover_gateway_info()

        logger.info(f"\n\n")
        logger.info(f"Discovered {gw_info}")

        # Discover Xcom devices
        devices = helper.discover_devices(getExtendedInfo=True, verbose=False)

        logger.info(f"\n\n")
        for device in devices:
            logger.info(f"Discovered {device}")

        # Log diagnostic information
        diag = api.get_diagnostics()
        logger.info(f"Diagnostics: {diag}")

    finally:
        api.stop()
        dataset = None


RunHelper.run(main)  # main loop
