# Do not edit this file directly. It has been autogenerated from
# example_discover_moxa_async.py
import asyncio
import logging
import sys

from datetime import datetime

from pystuderxcom import AsyncXcomDiscover, XcomDiscover
from helper import RunHelper

# Setup logging to StdOut
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
logger = logging.getLogger(__name__)


def main():
    # Discover IP address of Xcom-LAN / Moxa
    # Can be usefull to open the Moxa NPort Web Config
    url = XcomDiscover.discoverMoxaWebConfig()
    if url:
        logger.info(f"Moxa NPort Web Config found at: {url}")
    else:
        logger.info(f"Moxa NPort Web Config not found")


RunHelper.run(main)  # main loop
