# Do not edit this file directly. It has been autogenerated from
# tests\xcom_testclient_tcp_async.py
"""xcom_api.py: communication api to Studer Xcom via LAN."""

import asyncio
import logging
import socket

from pystuderxcom import  (
    AsyncXcomFactory,
    XcomFactory,
    XcomApiTimeoutException,
    XcomApiReadException,
    XcomApiWriteException,
    XcomPackage,
)
import threading

from pystuderxcom.api_tcp import XcomApiTcp

_LOGGER = logging.getLogger(__name__)


DEFAULT_PORT = 54001
START_TIMEOUT = 30 # seconds
STOP_TIMEOUT = 5
REQ_TIMEOUT = 2
REQ_RETRIES = 3


##
## Class implementing Xcom-LAN TCP network protocol
##
class XcomTestClientTcp(XcomApiTcp):

    # We mostly have the same behavior as the TCP Server
    # Except ofcourse that we start as TCP Client, not Server...
    def start(self, timeout=START_TIMEOUT, wait_for_connect=True) -> bool:
        """
        Start the Xcom Client and connect to the Xcom Server
        """
        if not self._started:
            _LOGGER.info(f"Xcom TCP Client connect to port {self.port}")

            self._connection = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            self._connection.connect(("localhost", self.port))
            self._started = True
            self._connected = True
        else:
            _LOGGER.info(f"Xcom TCP Client already connected to port {self.port}")
        
        return True    


    def stop(self):
        """
        Stop connection to the the Xcom Server
        """
        _LOGGER.info(f"Stopping Xcom TCP Client")
        try:
            self._connected = False

            if self._connection is not None:
                self._connection.close()
                self._connection = None
    
        except Exception as e:
            _LOGGER.warning(f"Exception during closing of Xcom Client connection: {e}")

        self._started = False
        _LOGGER.info(f"Stopped Xcom TCP Test Client")
    

    def receivePackage(self) -> XcomPackage | None:
        return super()._receivePackage()


    def sendPackage(self, package: XcomPackage):
        return super()._sendPackage(package)
