# Do not edit this file directly. It has been autogenerated from
# src\pystuderxcom\api_serial_async.py
"""
xcom_api_serial.py: communication api to Studer Xcom via serial port.

NOTE: this is a draft implementation that has never been tested against a Xcom-RS232i.
      Unlike the XcomApiTcp and XcomApiUdp that have indeed been verified against a real Xcom-LAN.
"""

import asyncio
import binascii
import logging
import serial_asyncio



from .api_base_async import (
    AsyncXcomApiBase,
    XcomApiReadException,
    XcomApiTimeoutException,
    XcomApiWriteException,
)
from .api_base_sync import (
    XcomApiBase,
)
from .factory_async import (
    AsyncXcomFactory,
)
from .factory_sync import (
    XcomFactory,
)
from .protocol import (
    XcomPackage,
)
import threading


_LOGGER = logging.getLogger(__name__)


DEFAULT_PORT = 'COM3'   # For Windows, or '/dev/ttyUSB0' for Linux
DEFAULT_BAUDRATE = 115200
DEFAULT_DATA_BITS = 8
DEFAULT_STOP_BITS = serial_asyncio.serial.STOPBITS_ONE
DEFAULT_PARITY = serial_asyncio.serial.PARITY_NONE
START_TIMEOUT = 30 # seconds
STOP_TIMEOUT = 5
REQ_TIMEOUT = 3

SERIAL_TERMINATOR = b'\x0D\x0A' # from Studer Xcom documentation


##
## Class implementing Xcom-RS232i serial protocol
##
class XcomApiSerial(XcomApiBase):

    def __init__(self, port=DEFAULT_PORT, baudrate=DEFAULT_BAUDRATE):
        """
        Initialize a new XcomApiSerial object.
        """
        super().__init__()

        self.localPort = port
        self.baudrate = baudrate
        self._serial = None
        self._reader = None
        self._writer = None
        self._connected = False

        self._sendPackageLock = threading.Lock() # to make sure _sendPackage is never called concurrently


    def start(self, timeout=START_TIMEOUT, loop=None) -> bool:
        """
        Start the serial connection to the Xcom-RS232i client.
        """
        if not self._connected:
            _LOGGER.info(f"Xcom-RS232i serial connection start via {self.localPort}")

            # Open serial connection. Maybe need to set parity, stopbits, etc as well...
            raise NotImplementedError()

            self._connected = True
        else:
            _LOGGER.info(f"Xcom-RS232i serial connection already connected to {self.localPort}")
        
        return True


    def stop(self):
        """
        Stop listening to the the Xcom Client and stop the Xcom Server.
        """
        _LOGGER.info(f"Stopping Xcom-RS232i serial connection")
        try:
            self._connected = False

            raise NotImplementedError()    
        
        except Exception as e:
            _LOGGER.warning(f"Exception during closing of Xcom writer: {e}")

        self._reader = None
        self._writer = None
        _LOGGER.info(f"Stopped Xcom-RS232i serial Connection")
    

    def _sendPackage(self, request: XcomPackage, timeout=REQ_TIMEOUT, verbose=False) -> XcomPackage | None:
        """
        Send an Xcom package from Server to Client and wait for the response (or timeout).
        Throws:
            XcomApiWriteException
            XcomApiReadException
            XcomApiTimeoutException
        """
        raise NotImplementedError()

